-- AlterTable
ALTER TABLE "idea_address" ALTER COLUMN "street_address" DROP NOT NULL,
ALTER COLUMN "street_address_2" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "postal_code" DROP NOT NULL;

-- AlterTable
ALTER TABLE "idea_geo" ALTER COLUMN "lat" DROP NOT NULL,
ALTER COLUMN "lon" DROP NOT NULL;

-- AlterTable
ALTER TABLE "user_address" ALTER COLUMN "street_address" DROP NOT NULL,
ALTER COLUMN "street_address_2" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "postal_code" DROP NOT NULL;

-- AlterTable
ALTER TABLE "user_geo" ALTER COLUMN "lat" DROP NOT NULL,
ALTER COLUMN "lon" DROP NOT NULL;
